---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prow-debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prow-debug
rules:
- apiGroups:
  - "prow.k8s.io"
  resources:
  - "prowjobs"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods"
  - "pods/log"
  - "pods/portforward"
  verbs:
  - "get"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prow-debug
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: prow-debug
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: prow-debug
  namespace: kubevirt-prow-jobs
